name: Run on Windows and macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run your project
      run: |
        python main.py  
